[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.10"
anyhow = "1.0.48"
serde_derive = "1.0.130"
serde_json = "1.0.71"
serde = "1.0.130"
